AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - test/fixtures/**/*
    - test/functions.rb

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/IndentHeredoc:
  Enabled: false
