language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
script: "script/cibuild"
sudo: false
cache: bundler
before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  # workaround for https://github.com/travis-ci/travis-ci/issues/7204
  - test $TRAVIS_RUBY_VERSION ">" 2.3 && gem update --system || true
